version: '3.3'

services:
  web:
    build:
      context: .
      dockerfile: freeins-website/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    volumes:
      - ./freeins-website:/app
      - /app/node_modules
    restart: unless-stopped
